### ISSUE TITLE
Not responsive on mobile

### ISSUE THREAD

**Issue by ghost** [lulu38m/StatsDisplayAPI#1]
![IMG_1302](https://github.com/user-attachments/assets/641c3e29-041d-4767-a7ad-b954faa48532)

**Comment by lulu38m** [comment]
Thank you, I hadn't realised that it wasn't responsive on mobile. 
I'm going to change that !

**Comment by lulu38m** [comment]
#
<img width="496" alt="Capture d’écran 2024-12-02 à 11 39 46" src="https://github.com/user-attachments/assets/c46b0daa-c303-4e75-a64b-43e5b1e899c2">

**Comment by ghost** [comment]
okay sorry for being rude

**Comment by ghost** [comment]
um now it is more broken
